### ISSUE TITLE
Minimum supported environments out of sync with Gallery

### ISSUE THREAD

**Issue by nschonni** [ALM-Rangers/Work-Item-Details-Widget-Extension#6]
The README states "Visual Studio Team Services", but on the actual gallery page, it lists "Team Foundation Server" as well.
Not sure which is correct.

**Comment by wpschaub** [comment]
We updated the README to match the gallery overview. The "works with" section on the gallery is correct.

**Comment by nschonni** [comment]
👍 Thanks!
